import AuthProvider from "../../api/auth/AuthContext";
import CartProvider from "../../contexts/CartContext";
import FavoriteProvider from "../../contexts/FavoriteContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <AuthProvider>
        <CartProvider>
          <FavoriteProvider>
            <html lang="en">
              <body>{children}</body>
            </html>
          </FavoriteProvider>
        </CartProvider>
      </AuthProvider>
  )
}
