import {AlertProvider, WebSocketProvider} from "components";
import {AuthProvider} from "components";
import {CustomThemeProvider} from "ui";

export const metadata = {
    title: 'Courier portal',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <CustomThemeProvider>
            <AlertProvider>
                <AuthProvider userRole="COURIER" registerPath="register-courier">
                    <WebSocketProvider senderRole="COURIER">
                        <html lang="en" style={{margin: 0, padding: 0}}>
                        <body style={{margin: 0, padding: 0}}>
                        {children}
                        </body>
                        </html>
                    </WebSocketProvider>
                </AuthProvider>
            </AlertProvider>
        </CustomThemeProvider>
    )
}
