import {AuthProvider} from "components";
import CartProvider from "../../contexts/CartContext";
import FavoriteProvider from "../../contexts/FavoriteContext";
import {WebSocketProvider} from "components";
import ProfilePictureProvider from "../../contexts/ProfilePictureContext";

export const metadata = {
    title: 'Fresh Corner',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <AuthProvider userRole="CLIENT" registerPath="register-client">
            <WebSocketProvider senderRole="CLIENT">
                <CartProvider>
                    <FavoriteProvider>
                        <ProfilePictureProvider>
                            <html lang="en" style={{margin: 0, padding: 0}}>
                            <body style={{margin: 0, padding: 0}}>
                            {/*<NavigationBar />*/}
                            {children}
                            {/*<Footer />*/}
                            </body>
                            </html>
                        </ProfilePictureProvider>
                    </FavoriteProvider>
                </CartProvider>
            </WebSocketProvider>
        </AuthProvider>
    )
}
