import {AuthProvider} from "components";
import CustomThemeProvider from "../../context/ThemeContext";

export const metadata = {
  title: 'Admin Portal',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <CustomThemeProvider>
          <AuthProvider userRole="ADMIN">
                <html lang="en" style={{margin: 0, padding: 0}}>
                  <body style={{margin: 0, padding: 0}}>
                    {children}
                  </body>
                </html>
          </AuthProvider>
      </CustomThemeProvider>
  )
}
