import AuthProvider from "../../api/auth/AuthContext";
import WebSocketProvider from "../../contexts/WebSocketContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <AuthProvider>
          <WebSocketProvider>
            <html lang="en" style={{margin: 0, padding: 0}}>
              <body style={{margin: 0, padding: 0}}>
                {children}
              </body>
            </html>
          </WebSocketProvider>
      </AuthProvider>
  )
}
